[package]
authors = ["esu"]
edition = "2024"
name = "DiscordBot"
version = "1.0.0"

[dependencies]
serenity = {version = "0.12"}
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
